modLoader = "javafml"
loaderVersion = "[31,)"
license = "LGPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/Fallen-Breath/classic-minecraft-icon"
authors = "Fallen_Breath"
description = '''
Bring back the classic crafting table window icon of Minecraft
'''
logoFile = "mod_icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"
